# This workflow runs the test.
#
# Trigger this workflow by pushing commits or by opening 
# a pull request.
name: Test
on: 
  push:
  pull_request:
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install latest version of go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Get latest siegfried signature
        run: wget https://www.itforarchivists.com/siegfried/latest
      - name: Run test
        run: |
          go mod init github.com/richardlehane/sfs3
          go mod tidy
          go test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: eu-central-1
          AWS_BUCKET: siegfried-s3-test
          AWS_OBJECT: IMG-20220331-WA0003.jpg
          
